- name: Launch app
  docker_container:
    name: backend
    state: started
    image: fabiensolde/mylittleproject:simple-api
    pull: yes
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_USERNAME: "{{db_user}}"
      SPRING_DATASOURCE_PASSWORD: "{{db_pwd}}"
      SPRING_DATASOURCE_URL: "{{db_url}}"
