- name: Launch app
  docker_container:
    name: backend
    state: started
    image: fabiensolde/mylittleproject:simple-api
    pull: yes
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_DATASOURCE_URL: "{{ db_url }}"
